name: test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [
          macOS-latest,
          ubuntu-latest,
          windows-latest
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Install googletest
        uses: ./
        with:
          googletest_tag: 'release-1.11.0'
      - name: configure test
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release . -B build
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake -T v143,host=x64 -A x64 . -B build
          else
            cmake -DCMAKE_BUILD_TYPE=Release . -B build
          fi
        working-directory: test
        shell: bash
      - name: build test
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake --build . --config Release
          else
            cmake --build .
          fi
        working-directory: test/build
        shell: bash
      - name: run test
        run:
          ./testbed
        working-directory: test/build
        shell: bash